### ISSUE TITLE
How do you compare As-Consistent-As-Possibble to As-Conformal-As-Possible?

### ISSUE THREAD

**Issue by MaxMayya** [gaolinorange/Automatic-Unpaired-Shape-Deformation-Transfer#11]
First of all, I have to say that I'm a fan of your method. I recently crossed the following article in the same spirit as yours

> Yusuke Yoshiyasu, Wan-Chun Ma, Eiichi Yoshida, and Fumio Kanehiro. "As-Conformal-As-Possible Surface Registration." Computer Graphics Forum. Vol. 33. No. 5. 2014

I'm asking this question because the article was not cited in your work. How do you compare your ACAP to theirs?

Thank you again

**Comment by MaxMayya** [comment]
Okay, I think my question was not relevant. Even though the work of 2014 could be seen as in the same spirit as the work here, a main difference is that the aim is to establish full correspondence between two meshes. Also, they indirectly resolve large rotations by using a coarse-to-fine schema while this work addresses it directly through the integer optimisation.

**Comment by chaurasiavikash** [comment]
Hi, 

I am wondering if a working code is publicly available.

**Comment by tommaoer** [comment]
> Hi,
> 
> I am wondering if a working code is publicly available.

Please refer to this [issue](https://github.com/gaolinorange/Automatic-Unpaired-Shape-Deformation-Transfer/issues/15#issuecomment-2543455024), thanks
