### ISSUE TITLE
Dataset in the Paper

### ISSUE THREAD

**Issue by seokg** [gaolinorange/Automatic-Unpaired-Shape-Deformation-Transfer#13]
Hi, I was going through the paper and wondered what kind of dataset did you used for Fig. 25 and Fig.26.
Is it something that we can download online like MPI DYNA?

**Comment by tommaoer** [comment]
Yes, the human data comes from the MPI DYNA, the person ID can be found in our paper. The face data comes from the paper https://grail.cs.washington.edu/projects/stfaces/. You can download it by yourself.

Jie
