### ISSUE TITLE
有没有成功跑起来的啊

### ISSUE THREAD

**Issue by zsl1996** [gaolinorange/Automatic-Unpaired-Shape-Deformation-Transfer#2]
CoMISo的依赖多到爆炸啊，cmake不出来。
想问下
![image](https://user-images.githubusercontent.com/31581150/47347137-36ca1880-d6e1-11e8-9d45-5e8eb6e686c8.png)
这些应该都是在windows上配置的吧，windows上的代码最后生成是什么？source与target的mesh文件吗？
linux上要跑的只是VC-GAN网络是吗

**Comment by maoyali** [comment]
我看到这些依赖真的是吓怕了，不知道这个代码在VS2013上能不能用，为啥我的Eigen.h一直编译不过啊，我进入Eigen 3.3.3 文件夹也找不到相应的.h文件？这个配置好跑出来的应该就是为了得到编译好的.exe文件,方便后续特征提取用？

**Comment by wdear** [comment]
@zsl1996  CoMISo我在编译OpenBLAS的时候卡住了，请问你目前还有进展吗？o(╯□╰)o

**Comment by zsl1996** [comment]
放弃了，换其他思路了，(´▽｀)ノ，你加油吧




获取 Outlook for Android







On Tue, Dec 18, 2018 at 4:12 PM +0800, "wdear" <notifications@github.com> wrote:












@zsl1996  CoMISo我在编译OpenBLAS的时候卡住了，请问你目前还有进展吗？o(╯□╰)o
