### ISSUE TITLE
Request for 2 .mat files

### ISSUE THREAD

**Issue by fasogbon** [gaolinorange/Automatic-Unpaired-Shape-Deformation-Transfer#8]
Thank you for this work. Can you provide an example .mat (cat and horse etc), no need for the full dataset. I want to debug the code without the need to run the feature generation codes in matlab/windows. Thanks

**Comment by tommaoer** [comment]
Please refer to this [link](https://github.com/gaolinorange/Automatic-Unpaired-Shape-Deformation-Transfer/issues/6#issuecomment-544341974). I provide the demo data of Fig.22 on the google drive. Please check it.

**Comment by fasogbon** [comment]
Thank you a million
